package com.incloud.hcp.jco.consultaGeneral.dto;

public class ConsultaGeneralOptions {
    public static String CONSGENCODTIPRE="CDEMB = '";
    public static String CONSGENLISTEQUIP="CDEMB = '";
    public static String CONSGENLISTEQUIP_="' AND ERGEQ = 'S'";
    public static String CONSGENCOOZONPES="CDZPC LIKE '";
    public static String CONSGENPESDECLA="NRMAR = '";
    public static String CONSGENPESDECLA_="' AND NREVN = '";
    public static String CONSGENLISTBODE="CDEMB = '";
    public static String CONSGENLISTBODE_="' AND ERGBO = 'S'";
    public static String CONSGENPESBODE="NRMAR = '";
    public static String CONSGENPESBODE_="' AND NREVN  = '";
    public static String CONSGENPUNTDES="ESREG = 'S' AND CDPTA = '";
    public static String CONSGENPESDESC="NRDES = '";
    public static String CONSGENCALENTEMP="FHCAL LIKE '";
    public static String CONSGENCLDRTEMPFECHA="FHCAL BETWEEN '";
    public static String CONSGENCONSTLAT="CDCNS = 4";
    public static String CONSGENCONSTLAT2=" OR CDCNS = 5";
    public static String CONSGENCONSTLAT3=" OR CDCNS = 6";
    public static String CONSGENCONSTLAT4=" OR CDCNS = 7";
    public static String CONSGENDPTO = "SPRAS EQ 'ES' AND LAND1 EQ 'PE'";
    public static String CONSGENMAREAANT_OPTION1 = "NRMAR < ";
    public static String CONSGENMAREAANT2_OPTION1 = " AND CDEMB LIKE '";
    public static String CONSGENMAREAANT2_OPTION2 = "CDEMB = '";
    public static String CONSGENEVENTANT = "NRMAR = ";
    public static String CONSGENNRORESERVA = "NRMAR = ";
    public static String CONSGENNRORESERVA2 = " AND ESRSV EQ 'S'";
    public static String CONSGENLISTSINIESTROS = "NRMAR = ";
    public static String CONSGENLISTSINIESTROS2 = " AND NREVN = ";
    public static String CONSGENLISTSINIESTROS3=" AND SPRAS EQ 'S'";
    public static String CONSGENVERIFTEMP="CDTPC = '";
    public static String CONSGENVERIFTEMP2=" AND FHCAL LIKE '";
    public static String CONSGENTEMP="CDTPC = '";
    public static String CONSGENTEMP2=" AND FHCAL LIKE '";
    public static String CONSGENCAPATANBARCA="CDEMB = '";
    public static String CONSGENMILLASLIT="LATGR = '";
    public static String CONSGENMILLASLIT2=" AND LATMI >= '";
    public static String CONSGENMILLASLIT3=" AND LATMI < '";
    public static String CONSGENPERMISOZARPE="CDEMB LIKE '";
    public static String CONSGENPERMISOZARPE2=" AND CDTPM LIKE 'Z'";
    public static String CONSGENARMADOR="CDEMP LIKE '";
    public static String CONSGENARMADOR2=" AND ESREG = 'S'";
    public static String CONSGENOBTTALLAMIN="CDSPC eq '";
    public static String CONSGENTEMPVEDA="CDTPC = 'V' AND FHCAL LIKE '";
    public static String CONSGENBSQTRIPU="WERKS EQ '";
    public static String CONSGENBSQTRIPU1="CDRTR EQ '" ;
    public static String CONSGENBSQTRIPU2="ABKRS EQ 'TT' AND CENTRO EQ '";
    public static String CONSGENPROVEEDORES="CDPTA = '";
    public static String CONSGENPROVEEDORES2="' AND CDALM = ";
    public static String CONSGENERRDSCG="NRDES = '";
    public static String CONSGENERRDSCG2=" AND INDTR = 'P' AND ESREG = 'S' AND NRDES NE '' AND CMIN EQ 'E'";

}
